spring:
  kafka:
    bootstrap-servers: k7c207.p.ssafy.io:29092
    properties:
      spring:
        json:
          value:
            default:
              type: kr.co.sys4u.app.dto.QueuedMessage
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
server:
  port: 8081
